    
spring: 
  datasource: 
    url: jdbc:mysql://47.106.68.40:3306/photo-management-system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

filePath: 
  Album: D:/nginx/html/photo-managemen-system/html/img/Album/
  mv: D:/nginx/html/photo-managemen-system/html/mv/
 
fileURL: 
  Album: http://127.0.0.1:81/static_html/img/Album/
  mv: http://127.0.0.1:81/static_html/mv/
  
