spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.68.40:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: test
    password: test
    # 连接池
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50

  # redis缓存配置
  redis:
    host: localhost
    database: 0
    # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    port: 6379
    password:
    # 连接超时时间（毫秒）
    # timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

# 端口路径
server:
  port: 8888
  servlet:
    context-path: /photographer

# mybatis配置
#mybatis&&通用Mapper
#扫描实力类的所在包

mybatis:
  type-aliases-package: top.huangqsh.business.**.entity
  mapper-locations: classpath:mapper/*.xml
  not-empty: false
  identity: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



