    
spring: 
  datasource: 
    url: jdbc:mysql://47.106.68.40:3306/photo-management-system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

filePath: 
  Album: /usr/local/webserver/nginx/html/photo-management-system/html/img/album/
  mv: /usr/local/webserver/nginx/html/photo-management-system/html/mv/
 
fileURL: 
  Album: https://huangqsh.top/static_html/img/album/
  mv: https://huangqsh.top/static_html/mv/
  
